version: 2

builds:
  - goos:
      - linux
      - darwin
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.BuildDate={{.Date}}

brews:
  - repository:
      owner: mrtimp
      name: homebrew-formulas
    directory: Formula
    homepage: "https://github.com/mrtimp/gojen"
    description: "Go project generator"
    commit_author:
      name: mrtimp
      email: timp@unfuddle.nz
